<?php

/**
 * @file
 * Webform Gmap Field module.
 */

/**
 * Implements hook_library_info_alter().
 */
function webform_gmap_field_library_info_alter(&$libraries, $extension) {
  if ($extension == 'webform_gmap_field') {
    $api_key = \Drupal::config('webform_gmap_field.config')->get('api_key');
    if ($api_key) {
      $libraries['global']['js']['//maps.googleapis.com/maps/api/js?callback=initMap&libraries=&v=weekly&key=' . $api_key] = [
        'type' => 'external',
      ];
    }
  }
}
