<?php

use Drupal\Core\Form\FormStateInterface;

function invoices_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_contacts_form') {
    $form['actions']['submit']['#value'] = t('Dodaj pravno lice');

    $firma_id = \Drupal::service('session')->get('company_id');

    if ($firma_id && isset($form['field_firma_id']['widget'][0])) {
      $firma_node = \Drupal::entityTypeManager()->getStorage('node')->load($firma_id);
      if ($firma_node) {
        $form['field_firma_id']['widget'][0]['target_id']['#default_value'] = $firma_node;
      }
      $form['field_firma_id']['#access'] = FALSE;
    }

    $form['actions']['submit']['#submit'][] = 'invoices_contacts_form_submit_redirect';
  }
}

function invoices_contacts_form_submit_redirect(array &$form, FormStateInterface $form_state) {
  $form_state->setRedirectUrl(\Drupal\Core\Url::fromUserInput('/company-contact'));
}