#!/bin/bash

echo "[/] Starting..."

echo "..."

fin up > /dev/null 2>&1
echo "..."

echo "[/] Dumping database..."

echo "..."
mkdir -p dbdump
fin drush sql:dump --result-file=dbdump/dump.sql
echo "..."

echo "[\] Dump completed!"

echo "[/] Exporting config..."

echo "..."
fin drush cex -y > /dev/null 2>&1

echo "..."

echo "[\] Config exported!"

echo "[✓] Done!"
