<?php


function registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id === 'user_login_form') {
    // Change the label of the username field.
    if (isset($form['name'])) {
      $form['name']['#title'] = t('Korisničko ime');
    }
    if(isset($form['pass'])){
      $form['pass']['#title'] = t('Lozinka');
    }

    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#value'] = t('Prijavi se');
    }

    $form['actions']['register'] = [
      '#type' => 'link',
      '#title' => t('Registruj se'),
      '#url' => \Drupal\Core\Url::fromRoute('user.register'), // Link to the registration page.
      '#attributes' => [
        'class' => ['btn', 'btn-success'], // Add button styling.
      ],
    ];
  }
}